### ISSUE TITLE
github htmlpreview BUG

### ISSUE THREAD

**Issue by LFF5644** [nodi-andy/browser-factory#1]
![grafik](https://user-images.githubusercontent.com/109358910/216053984-aab81663-7431-4fd5-b887-8af3c2d700a4.png)

**Comment by LFF5644** [comment]
same error in "microsoft Edge"

**Comment by nodi-andy** [comment]
github preview doesnt support "modules" :(... The current version is here: http://mynodi.com/browser-factory/

It would be nice if github preview would support modules and ES6 can be used.

**Comment by nodi-andy** [comment]
See here: http://factory.mynodi.com/
Mobile support is also done
