### ISSUE TITLE
Zero resources problem

### ISSUE THREAD

**Issue by nodi-darko** [nodi-andy/browser-factory#2]
The oven can have 0 from a resource.
![221945293-b9e611fe-1e01-41b0-9ca3-fbd4dee70a59](https://user-images.githubusercontent.com/19575988/222005668-b37ec873-2b61-4e24-bd63-75b9c283d20e.jpeg)

**Comment by nodi-darko** [comment]
Bug beim Herstellen Ressourcenmenge wird falsch angezeigt. 
![WhatsApp Image 2023-02-28 at 16 01 53](https://user-images.githubusercontent.com/71972242/221945513-039b4fcc-bcf7-4680-bd1c-a93a9622741e.jpeg)

**Comment by nodi-darko** [comment]
![WhatsApp Image 2023-02-28 at 16 03 20](https://user-images.githubusercontent.com/71972242/221945627-e4727aa3-e62a-45ea-ad63-50113876cfef.jpeg)
Bug 3, Ofen wird nicht aktualisiert.

**Comment by nodi-darko** [comment]
![WhatsApp Image 2023-02-28 at 16 06 03](https://user-images.githubusercontent.com/71972242/221945832-6573386b-3ea8-4dc9-a02d-39d57d957709.jpeg)
Bug 4, beim Ofen ist eine komische Zeile entstanden

**Comment by nodi-andy** [comment]
fixed in 0.1.1
