### ISSUE TITLE
Oven do not work

### ISSUE THREAD

**Issue by nodi-darko** [nodi-andy/browser-factory#8]
The oven do not work sometimes

![221947871-9be4f015-0efc-40cc-855c-a77f1da9791b](https://user-images.githubusercontent.com/19575988/222138800-a601bc5c-1f0c-4d65-94e7-877c8486c741.jpeg)

**Comment by nodi-andy** [comment]
Duplicated: https://github.com/nodi-andy/browser-factory/issues/4
